### ISSUE TITLE
Laminas\Hydrator\ClassMethodsHydrator not found

### ISSUE THREAD

**Issue by matthieu-antoniol** [LM-Commons/LmcUser#27]
Hello, i have implemented LmcUser in my company in the place of an old zfc user.

I managed to make nearly everything work. (Authentication, login session...)
It was until i tried to create an user account.

I received the very same error when trying to use the hydrator as i used to.
I tried to put the hydrator in my factories, in my config nothing works.

It seems to be related to the register form.

The problems seems similar to : 

> https://github.com/LM-Commons/LmcUser/issues/15

Here is the exact error.
```
<?php
CONTROLLER:PublicWebSite\Controller\User
FILE :my_site/vendor/laminas/laminas-servicemanager/src/ServiceManager.php (line: 588)

TRACE:
#0 my_site/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(664): Laminas\ServiceManager\ServiceManager->getFactory('Laminas\\Hydrato...')
#1 my_site/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(230): Laminas\ServiceManager\ServiceManager->doCreate('Laminas\\Hydrato...')
#2 my_site/vendor/lm-commons/lmc-user/src/LmcUser/Factory/UserHydrator.php(19): Laminas\ServiceManager\ServiceManager->get('lmcuser_base_hy...')
#3 my_site/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(665): LmcUser\Factory\UserHydrator->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'lmcuser_user_hy...', NULL)
#4 my_site/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(230): Laminas\ServiceManager\ServiceManager->doCreate('lmcuser_user_hy...')
#5 my_site/vendor/lm-commons/lmc-user/src/LmcUser/Service/User.php(296): Laminas\ServiceManager\ServiceManager->get('lmcuser_registe...')
#6 my_site/module/PublicWebSite/src/PublicWebSite/Controller/UserController.php(181): LmcUser\Service\User->getFormHydrator()
#7 my_site/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): PublicWebSite\Controller\UserController->jsonRegisterAction()
#8 my_site/vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#9 my_site/vendor/laminas/laminas-eventmanager/src/EventManager.php(188): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#10 my_site/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(105): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#11 my_site/vendor/laminas/laminas-mvc/src/DispatchListener.php(138): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#12 my_site/vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#13 my_site/vendor/laminas/laminas-eventmanager/src/EventManager.php(188): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#14 my_site/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#15 my_site/public/index.php(47): Laminas\Mvc\Application->run()
#16 {main}

 Exception:
Unable to resolve service "Laminas\Hydrator\ClassMethodsHydrator" to a factory; are you certain you provided it during configuration?


```

dependencies installed
"laminas/laminas-servicemanager": "^3.4", (3.6.4)
 "lm-commons/lmc-user": "^3.3", (3.3.3)
 
 Any idea how i could fix the problem?
 
 Thank you very much for your help and nice work by the way.
 
 Matthieu Antoniol

**Comment by matthieu-antoniol** [comment]
Ok seems the pre release fixed the issue.
I will pass in 3.4.0 to solve my issue.
https://github.com/LM-Commons/LmcUser/releases/tag/3.4.0

Sorry for the troubles.
